#!/usr/bin/env bash
#check if argument is provided
#extract IP address from the argument
#ping Ip address 5 times

if [ $# -ne 1 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

ip_address=$1

ping -c 5 "$ip_address"
