#!/usr/bin/env bash
#Display a header
# Use the ps command to display the list of processes
echo "USER        PID  PPID  %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND"

ps -eo user,pid,ppid,%cpu,%mem,vsz,rss,tty,stat,start,time,cmd --forest
