#!/usr/bin/env bash
#this is a for loop used  to iterate over numbers from 1 to 100
#used to check if number is a multiple of both 3 and 5
#if not then display the number

for ((i=1; i<=100; i++));
do
    if (( i % 3 == 0 )) && (( i % 5 == 0 ));
then
        echo "FizzBuzz"

    elif (( i % 3 == 0 ));
then
        echo "Fizz"

    elif (( i % 5 == 0 ));
then
        echo "Buzz"

    else
        echo "$i"
    fi
done
