#!/bin/bash

#this is a while loop used  to display "Best School" 10 times
# Checks if the iteration is 9th

counter=0

while [ $counter -lt 10 ];
do
    if [ $counter -eq 8 ];
then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    ((counter++))
done
